In [1]:
import json
import numpy as np
import pandas as pd
import networkx as nx
from random import randint

In [2]:
def random_json():
    with open('result.json') as fp:
        data = json.load(fp)
        questions = data["letters"]["part one"]["meem"]["questions"]
        random_index = randint(0, len(questions)-1)
        return questions[random_index]['question']

In [3]:
jdata = json.loads(open ('../../data/trips_europeans_pp.json').read())

FileNotFoundError: [Errno 2] No such file or directory: '../../data/trips_europeans_pp.json'

In [4]:
length = len(jdata["trips"])
df = pd.DataFrame(np.zeros(shape=(1,4)))

NameError: name 'jdata' is not defined

In [21]:
init_trip = jdata["trips"][0]
random_index = randint(0, length-1)
print(random_index)
print(jdata["trips"][random_index])

52416
{'trip_id': '878f549ea3', 'traveler_id': '53326698', 'dataset': 'twitter', 'traveler_home': 'NL', 'first_checkin': '2017-03-08 14:17:15', 'last_checkin': '2017-03-11 07:25:51', 'duration': 4, 'num_checkins': 2, 'checkin_density': 0.5, 'checkin_frequency': 0.5, 'num_distinct_countries': 2, 'num_blocks': 2, 'blocks': [{'country_code': 'AT', 'first_checkin': '2017-03-08 14:17:15', 'last_checkin': '2017-03-08 14:17:15', 'duration': 1, 'num_checkins': 1}, {'country_code': 'DE', 'first_checkin': '2017-03-11 07:25:51', 'last_checkin': '2017-03-11 07:25:51', 'duration': 1, 'num_checkins': 1}], 'mean_checkin_distance': 110.64, 'median_checkin_distance': 110.64, 'std_checkin_distance': 0, 'mean_checkin_duration': 1028.6, 'median_checkin_duration': 1028.6, 'std_checkin_duration': 0, 'mean_displacement': 734.58, 'median_displacement': 734.58, 'std_displacement': 52.24}

In [26]:
ind = 1
init_trip = jdata["trips"][0]
df = pd.DataFrame([ind,init_trip["trip_id"],init_trip["traveler_home"],init_trip["first_checkin"],init_trip["last_checkin"]]).T

for i in range(100):
    random_index = randint(0, length-1)
    trip = jdata["trips"][random_index]
    temp_df = pd.DataFrame([ind,trip["trip_id"],trip["traveler_home"],trip["first_checkin"],trip["last_checkin"]]).T
    df = df.append(temp_df, ignore_index=True)
    for c in trip["blocks"]:
        temp_df2 = pd.DataFrame([ind,trip["trip_id"],c.get("country_code"), c.get("first_checkin"), c.get("last_checkin")]).T
        df=df.append(temp_df2, ignore_index=True)
    ind = ind+1

In [27]:
df

       0           1   2                    3                    4
0      1  dd17ccd818  NL  2018-03-28 11:08:57  2018-03-29 08:59:42
1      1  1da68a6626  IT  2017-11-18 09:57:12  2017-11-25 07:53:19
2      1  1da68a6626  IT  2017-11-18 09:57:12  2017-11-25 07:53:19
3      2  ea6db180aa  DE  2018-07-13 09:05:40  2018-07-17 06:06:00
4      2  ea6db180aa  AT  2018-07-13 09:05:40  2018-07-17 06:06:00
..   ...         ...  ..                  ...                  ...
242   98  e8706d1400  FR  2018-07-25 10:55:53  2018-07-26 14:04:50
243   99  f50d4ce10e  DE  2018-06-11 14:31:00  2018-06-13 20:47:29
244   99  f50d4ce10e  DE  2018-06-11 14:31:00  2018-06-13 20:47:29
245  100  758a08f2c8  TR  2018-02-04 11:15:35  2018-02-05 08:50:37
246  100  758a08f2c8  TR  2018-02-04 11:15:35  2018-02-05 08:50:37

[247 rows x 5 columns]

In [289]:
df1 = pd.read_csv("../../data/from_to_date.csv")
df2 = pd.read_csv("../../data/from_to_date2.csv")
df3 = pd.read_csv("../../data/from_to_date3.csv")
df4 = pd.read_csv("../../data/from_to_date4.csv")
df5 = pd.read_csv("../../data/from_to_date5.csv")
df6 = pd.read_csv("../../data/from_to_date6.csv")
df7 = pd.read_csv("../../data/from_to_date7.csv")
df8 = pd.read_csv("../../data/from_to_date8.csv")
df9 = pd.read_csv("../../data/from_to_date9.csv")
df10 = pd.read_csv("../../data/from_to_date7.csv")
df11 = pd.read_csv("../../data/from_to_date8.csv")
df12 = pd.read_csv("../../data/from_to_date9.csv")

In [290]:
travel_df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])
travel_df.columns = ["trip_number","trip_id","node","First_checkin","Last_checkin"]
travel_df

        trip_number     trip_id node        First_checkin         Last_checkin
0                 1  d8799616e3   US  2018-10-03 07:18:32  2018-10-06 05:33:12
1                 1  7dee487f12   US  2018-07-11 21:09:27  2018-07-12 00:23:41
2                 1  7dee487f12   US  2018-07-11 21:09:27  2018-07-11 21:09:27
3                 1  7dee487f12   US  2018-07-12 00:23:41  2018-07-12 00:23:41
4                 2  512a66d10e   EC  2017-07-08 15:32:39  2017-07-09 18:05:26
...             ...         ...  ...                  ...                  ...
151319        30000  a124677fc3   MX  2018-12-10 16:39:44  2018-12-12 20:14:24
151320        30000  a124677fc3   MX  2018-12-10 16:39:44  2018-12-10 17:20:27
151321        30000  a124677fc3   MX  2018-12-11 13:41:43  2018-12-11 13:41:43
151322        30000  a124677fc3   MX  2018-12-11 16:26:33  2018-12-11 16:38:33
151323        30000  a124677fc3   MX  2018-12-11 23:04:14  2018-12-12 20:14:24

[1819581 rows x 5 columns]

In [3]:
travel_df = pd.read_csv("../csv/global_travel_df.csv").iloc[:,1:]

In [4]:
travel_df.iloc[100:150]

     trip_number     trip_id node        First_checkin         Last_checkin
100           28  c33ed71d41   US  2018-09-01 15:14:17  2018-09-03 02:16:07
101           28  c33ed71d41   US  2018-09-01 15:14:17  2018-09-02 04:56:12
102           28  c33ed71d41   US  2018-09-03 02:16:07  2018-09-03 02:16:07
103           29  2c6adaf0ad   US  2018-11-28 02:27:44  2018-12-06 19:08:17
104           29  2c6adaf0ad   US  2018-11-28 02:27:44  2018-11-28 04:32:48
105           29  2c6adaf0ad   GB  2018-11-28 11:11:55  2018-11-28 11:11:55
106           29  2c6adaf0ad   US  2018-11-28 11:31:07  2018-11-28 11:31:07
107           29  2c6adaf0ad   GB  2018-11-28 11:31:58  2018-11-28 11:43:55
108           29  2c6adaf0ad   HR  2018-11-29 10:50:59  2018-12-04 10:10:37
109           29  2c6adaf0ad   GB  2018-12-04 14:59:10  2018-12-04 14:59:10
110           29  2c6adaf0ad   US  2018-12-05 00:02:47  2018-12-05 00:02:47
111           29  2c6adaf0ad   US  2018-12-05 12:02:11  2018-12-05 13:18:12
112           29  2c6adaf0ad   US  2018-12-06 01:55:25  2018-12-06 19:08:17
113           30  df7648aa9c   PH  2018-07-11 10:45:55  2018-07-12 04:40:22
114           30  df7648aa9c   TW  2018-07-11 10:45:55  2018-07-11 10:45:55
115           30  df7648aa9c   PH  2018-07-12 04:03:25  2018-07-12 04:08:24
116           30  df7648aa9c   PH  2018-07-12 04:40:22  2018-07-12 04:40:22
117           31  fbf17f57b9   US  2018-01-05 23:27:25  2018-01-07 04:51:55
118           31  fbf17f57b9   US  2018-01-05 23:27:25  2018-01-05 23:27:25
119           31  fbf17f57b9   US  2018-01-06 14:14:11  2018-01-07 04:51:55
120           32  9815bce201   US  2018-01-26 21:45:38  2018-01-28 00:51:59
121           32  9815bce201   US  2018-01-26 21:45:38  2018-01-28 00:51:59
122           33  2ae57d2d91   US  2017-12-08 00:05:31  2017-12-14 21:55:34
123           33  2ae57d2d91   US  2017-12-08 00:05:31  2017-12-08 00:05:31
124           33  2ae57d2d91   US  2017-12-08 23:12:12  2017-12-08 23:22:38
125           33  2ae57d2d91   US  2017-12-09 00:19:15  2017-12-09 00:19:15
126           33  2ae57d2d91   US  2017-12-09 23:37:01  2017-12-10 00:25:56
127           33  2ae57d2d91   US  2017-12-10 20:00:51  2017-12-10 20:00:51
128           33  2ae57d2d91   US  2017-12-10 21:32:04  2017-12-10 21:32:04
129           33  2ae57d2d91   US  2017-12-14 21:55:34  2017-12-14 21:55:34
130           34  a4a76835df   US  2018-12-29 21:32:17  2018-12-30 20:49:06
131           34  a4a76835df   US  2018-12-29 21:32:17  2018-12-30 20:49:06
132           35  133cb93dc3   US  2017-11-07 17:27:23  2017-11-11 17:50:35
133           35  133cb93dc3   US  2017-11-07 17:27:23  2017-11-11 17:50:35
134           36  772ca4d0ce   US  2017-12-13 21:07:56  2017-12-15 10:54:48
135           36  772ca4d0ce   US  2017-12-13 21:07:56  2017-12-13 21:07:56
136           36  772ca4d0ce   US  2017-12-15 10:54:48  2017-12-15 10:54:48
137           37  afc3f50089   BR  2019-03-09 21:31:30  2019-03-16 17:45:17
138           37  afc3f50089   BR  2019-03-09 21:31:30  2019-03-16 17:45:17
139           38  4dba774cd9   US  2018-07-04 04:07:21  2018-07-08 16:25:43
140           38  4dba774cd9   US  2018-07-04 04:07:21  2018-07-04 04:07:21
141           38  4dba774cd9   US  2018-07-07 06:23:29  2018-07-07 06:23:29
142           38  4dba774cd9   US  2018-07-08 16:25:43  2018-07-08 16:25:43
143           39  fe31a0a3d6   AU  2017-07-08 06:09:11  2017-07-09 05:01:24
144           39  fe31a0a3d6   AU  2017-07-08 06:09:11  2017-07-08 06:09:11
145           39  fe31a0a3d6   AU  2017-07-09 05:01:24  2017-07-09 05:01:24
146           40  9d39c0a760   US  2018-03-09 06:39:12  2018-03-18 06:23:32
147           40  9d39c0a760   US  2018-03-09 06:39:12  2018-03-09 06:39:12
148           40  9d39c0a760   US  2018-03-11 10:24:40  2018-03-11 10:24:40
149           40  9d39c0a760   US  2018-03-13 22:45:30  2018-03-14 00:30:45

In [327]:
# travel_df.to_csv("global_travel_df.csv")

In [22]:
# Create from / to / date dataframe.
# This takes < 1hour for european travel datasets
from datetime import timedelta 
from datetime import datetime

from_to_df=None
travel_start=0
travel_end=0
for i in range(1,len(travel_df)):
    if i % 1000 == 0:
        print(i)
    if(travel_df.iloc[i,0] != travel_df.iloc[i-1,0]):
        travel_start = travel_df.iloc[i,3]
        travel_end = travel_df.iloc[i,4]
    if (travel_df.iloc[i-1,2] !=travel_df.iloc[i,2]) and (travel_df.iloc[i,0]==travel_df.iloc[i-1,0]):
#         a= np.array([travel_df.iloc[i-1,2], travel_df.iloc[i,2], travel_df.iloc[i,3]])
        b =np.array([travel_df.iloc[i,0], travel_df.iloc[i,1], travel_df.iloc[i-1,2], travel_df.iloc[i,2], travel_df.iloc[i,3], travel_start, travel_end])
        if from_to_df is not None:
            from_to_df = np.vstack((from_to_df,b))
        else:
            from_to_df = b

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000
211000
212000
213000
214000
215000
216000
217000
218000
219000
220000
221000
222000
223000
224000
225000
226000
227000
228000
229000
230000
231000
232000
233000
234000
235000
236000
237000
238000
239000
240000
241000
242000
243000
244000
245000
246000
247000
248000
249000
250000
251000
252000
253000
254000
255000
256000
257000
258000
259000
260000
261000
262000
263000
264000
265000
266000
267000
268000
269000
270000
271000
272000
273000
274000
275000
276000
277000
278000
279000
280000
281000
282000
283000
284000
285000
286000
287000
288000
289000
290000
291000
292000
293000
294000
295000
296000
297000
298000
299000
300000
301000
302000
303000
304000
305000
306000
307000
308000
309000
310000
311000
312000
313000
314000
315000
316000
317000
318000
319000
320000
321000
322000
323000
324000
325000
326000
327000
328000
329000
330000
331000
332000
333000
334000
335000
336000
337000
338000
339000
340000
341000
342000
343000
344000
345000
346000
347000
348000
349000
350000
351000
352000
353000
354000
355000
356000
357000
358000
359000
360000
361000
362000
363000
364000
365000
366000
367000
368000
369000
370000
371000
372000
373000
374000
375000
376000
377000
378000
379000
380000
381000
382000
383000
384000
385000
386000
387000
388000
389000
390000
391000
392000
393000
394000
395000
396000
397000
398000
399000
400000
401000
402000
403000
404000
405000
406000
407000
408000
409000
410000
411000
412000
413000
414000
415000
416000
417000
418000
419000
420000
421000
422000
423000
424000
425000
426000
427000
428000
429000
430000
431000
432000
433000
434000
435000
436000
437000
438000
439000
440000
441000
442000
443000
444000
445000
446000
447000
448000
449000
450000
451000
452000
453000
454000
455000
456000
457000
458000
459000
460000
461000
462000
463000
464000
465000
466000
467000
468000
469000
470000
471000
472000
473000
474000
475000
476000
477000
478000
479000
480000
481000
482000
483000
484000
485000
486000
487000
488000
489000
490000
491000
492000
493000
494000
495000
496000
497000
498000
499000
500000
501000
502000
503000
504000
505000
506000
507000
508000
509000
510000
511000
512000
513000
514000
515000
516000
517000
518000
519000
520000
521000
522000
523000
524000
525000
526000
527000
528000
529000
530000
531000
532000
533000
534000
535000
536000
537000
538000
539000
540000
541000
542000
543000
544000
545000
546000
547000
548000
549000
550000
551000
552000
553000
554000
555000
556000
557000
558000
559000
560000
561000
562000
563000
564000
565000
566000
567000
568000
569000
570000
571000
572000
573000
574000
575000
576000
577000
578000
579000
580000
581000
582000
583000
584000
585000
586000
587000
588000
589000
590000
591000
592000
593000
594000
595000
596000
597000
598000
599000
600000
601000
602000
603000
604000
605000
606000
607000
608000
609000
610000
611000
612000
613000
614000
615000
616000
617000
618000
619000
620000
621000
622000
623000
624000
625000
626000
627000
628000
629000
630000
631000
632000
633000
634000
635000
636000
637000
638000
639000
640000
641000
642000
643000
644000
645000
646000
647000
648000
649000
650000
651000
652000
653000
654000
655000
656000
657000
658000
659000
660000
661000
662000
663000
664000
665000
666000
667000
668000
669000
670000
671000
672000
673000
674000
675000
676000
677000
678000
679000
680000
681000
682000
683000
684000
685000
686000
687000
688000
689000
690000
691000
692000
693000
694000
695000
696000
697000
698000
699000
700000
701000
702000
703000
704000
705000
706000
707000
708000
709000
710000
711000
712000
713000
714000
715000
716000
717000
718000
719000
720000
721000
722000
723000
724000
725000
726000
727000
728000
729000
730000
731000
732000
733000
734000
735000
736000
737000
738000
739000
740000
741000
742000
743000
744000
745000
746000
747000
748000
749000
750000
751000
752000
753000
754000
755000
756000
757000
758000
759000
760000
761000
762000
763000
764000
765000
766000
767000
768000
769000
770000
771000
772000
773000
774000
775000
776000
777000
778000
779000
780000
781000
782000
783000
784000
785000
786000
787000
788000
789000
790000
791000
792000
793000
794000
795000
796000
797000
798000
799000
800000
801000
802000
803000
804000
805000
806000
807000
808000
809000
810000
811000
812000
813000
814000
815000
816000
817000
818000
819000
820000
821000
822000
823000
824000
825000
826000
827000
828000
829000
830000
831000
832000
833000
834000
835000
836000
837000
838000
839000
840000
841000
842000
843000
844000
845000
846000
847000
848000
849000
850000
851000
852000
853000
854000
855000
856000
857000
858000
859000
860000
861000
862000
863000
864000
865000
866000
867000
868000
869000
870000
871000
872000
873000
874000
875000
876000
877000
878000
879000
880000
881000
882000
883000
884000
885000
886000
887000
888000
889000
890000
891000
892000
893000
894000
895000
896000
897000
898000
899000
900000
901000
902000
903000
904000
905000
906000
907000
908000
909000
910000
911000
912000
913000
914000
915000
916000
917000
918000
919000
920000
921000
922000
923000
924000
925000
926000
927000
928000
929000
930000
931000
932000
933000
934000
935000
936000
937000
938000
939000
940000
941000
942000
943000
944000
945000
946000
947000
948000
949000
950000
951000
952000
953000
954000
955000
956000
957000
958000
959000
960000
961000
962000
963000
964000
965000
966000
967000
968000
969000
970000
971000
972000
973000
974000
975000
976000
977000
978000
979000
980000
981000
982000
983000
984000
985000
986000
987000
988000
989000
990000
991000
992000
993000
994000
995000
996000
997000
998000
999000
1000000
1001000
1002000
1003000
1004000
1005000
1006000
1007000
1008000
1009000
1010000
1011000
1012000
1013000
1014000
1015000
1016000
1017000
1018000
1019000
1020000
1021000
1022000
1023000
1024000
1025000
1026000
1027000
1028000
1029000
1030000
1031000
1032000
1033000
1034000
1035000
1036000
1037000
1038000
1039000
1040000
1041000
1042000
1043000
1044000
1045000
1046000
1047000
1048000
1049000
1050000
1051000
1052000
1053000
1054000
1055000
1056000
1057000
1058000
1059000
1060000
1061000
1062000
1063000
1064000
1065000
1066000
1067000
1068000
1069000
1070000
1071000
1072000
1073000
1074000
1075000
1076000
1077000
1078000
1079000
1080000
1081000
1082000
1083000
1084000
1085000
1086000
1087000
1088000
1089000
1090000
1091000
1092000
1093000
1094000
1095000
1096000
1097000
1098000
1099000
1100000
1101000
1102000
1103000
1104000
1105000
1106000
1107000
1108000
1109000
1110000
1111000
1112000
1113000
1114000
1115000
1116000
1117000
1118000
1119000
1120000
1121000
1122000
1123000
1124000
1125000
1126000
1127000
1128000
1129000
1130000
1131000
1132000
1133000
1134000
1135000
1136000
1137000
1138000
1139000
1140000
1141000
1142000
1143000
1144000
1145000
1146000
1147000
1148000
1149000
1150000
1151000
1152000
1153000
1154000
1155000
1156000
1157000
1158000
1159000
1160000
1161000
1162000
1163000

1164000
1165000
1166000
1167000
1168000
1169000
1170000
1171000
1172000
1173000
1174000
1175000
1176000
1177000
1178000
1179000
1180000
1181000
1182000
1183000
1184000
1185000
1186000
1187000
1188000
1189000
1190000
1191000
1192000
1193000
1194000
1195000
1196000
1197000
1198000
1199000
1200000
1201000
1202000
1203000
1204000
1205000
1206000
1207000
1208000
1209000
1210000
1211000
1212000
1213000
1214000
1215000
1216000
1217000
1218000
1219000
1220000
1221000
1222000
1223000
1224000
1225000
1226000
1227000
1228000
1229000
1230000
1231000
1232000
1233000
1234000
1235000
1236000
1237000
1238000
1239000
1240000
1241000
1242000
1243000
1244000
1245000
1246000
1247000
1248000
1249000
1250000
1251000
1252000
1253000
1254000
1255000
1256000
1257000
1258000
1259000
1260000
1261000
1262000
1263000
1264000
1265000
1266000
1267000
1268000
1269000
1270000
1271000
1272000
1273000
1274000
1275000
1276000
1277000
1278000
1279000
1280000
1281000
1282000
1283000
1284000
1285000
1286000
1287000
1288000
1289000
1290000
1291000
1292000
1293000
1294000
1295000
1296000
1297000
1298000
1299000
1300000
1301000
1302000
1303000
1304000
1305000
1306000
1307000
1308000
1309000
1310000
1311000
1312000
1313000
1314000
1315000
1316000
1317000
1318000
1319000
1320000
1321000
1322000
1323000
1324000
1325000
1326000
1327000
1328000
1329000
1330000
1331000
1332000
1333000
1334000
1335000
1336000
1337000
1338000
1339000
1340000
1341000
1342000
1343000
1344000
1345000
1346000
1347000
1348000
1349000
1350000
1351000
1352000
1353000
1354000
1355000
1356000
1357000
1358000
1359000
1360000
1361000
1362000
1363000
1364000
1365000
1366000
1367000
1368000
1369000
1370000
1371000
1372000
1373000
1374000
1375000
1376000
1377000
1378000
1379000
1380000
1381000
1382000
1383000
1384000
1385000
1386000
1387000
1388000
1389000
1390000
1391000
1392000
1393000
1394000
1395000
1396000
1397000
1398000
1399000
1400000
1401000
1402000
1403000
1404000
1405000
1406000
1407000
1408000
1409000
1410000
1411000
1412000
1413000
1414000
1415000
1416000
1417000
1418000
1419000
1420000
1421000
1422000
1423000
1424000
1425000
1426000
1427000
1428000
1429000
1430000
1431000
1432000
1433000
1434000
1435000
1436000
1437000
1438000
1439000
1440000
1441000
1442000
1443000
1444000
1445000
1446000
1447000
1448000
1449000
1450000
1451000
1452000
1453000
1454000
1455000
1456000
1457000
1458000
1459000
1460000
1461000
1462000
1463000
1464000
1465000
1466000
1467000
1468000
1469000
1470000
1471000
1472000
1473000
1474000
1475000
1476000
1477000
1478000
1479000
1480000
1481000
1482000
1483000
1484000
1485000
1486000
1487000
1488000
1489000
1490000
1491000
1492000
1493000
1494000
1495000
1496000
1497000
1498000
1499000
1500000
1501000
1502000
1503000
1504000
1505000
1506000
1507000
1508000
1509000
1510000
1511000
1512000
1513000
1514000
1515000
1516000
1517000
1518000
1519000
1520000
1521000
1522000
1523000
1524000
1525000
1526000
1527000
1528000
1529000
1530000
1531000
1532000
1533000
1534000
1535000
1536000
1537000
1538000
1539000
1540000
1541000
1542000
1543000
1544000
1545000
1546000
1547000
1548000
1549000
1550000
1551000
1552000
1553000
1554000
1555000
1556000
1557000
1558000
1559000
1560000
1561000
1562000
1563000
1564000
1565000
1566000
1567000
1568000
1569000
1570000
1571000
1572000
1573000
1574000
1575000
1576000
1577000
1578000
1579000
1580000
1581000
1582000
1583000
1584000
1585000
1586000
1587000
1588000
1589000
1590000
1591000
1592000
1593000
1594000
1595000
1596000
1597000
1598000
1599000
1600000
1601000
1602000
1603000
1604000
1605000
1606000
1607000
1608000
1609000
1610000
1611000
1612000
1613000
1614000
1615000
1616000
1617000
1618000
1619000
1620000
1621000
1622000
1623000
1624000
1625000
1626000
1627000
1628000
1629000
1630000
1631000
1632000
1633000
1634000
1635000
1636000
1637000
1638000
1639000
1640000
1641000
1642000
1643000
1644000
1645000
1646000
1647000
1648000
1649000
1650000
1651000
1652000
1653000
1654000
1655000
1656000
1657000
1658000
1659000
1660000
1661000
1662000
1663000
1664000
1665000
1666000
1667000
1668000
1669000
1670000
1671000
1672000
1673000
1674000
1675000
1676000
1677000
1678000
1679000
1680000
1681000
1682000
1683000
1684000
1685000
1686000
1687000
1688000
1689000
1690000
1691000
1692000
1693000
1694000
1695000
1696000
1697000
1698000
1699000
1700000
1701000
1702000
1703000
1704000
1705000
1706000
1707000
1708000
1709000
1710000
1711000
1712000
1713000
1714000
1715000
1716000
1717000
1718000
1719000
1720000
1721000
1722000
1723000
1724000
1725000
1726000
1727000
1728000
1729000
1730000
1731000
1732000
1733000
1734000
1735000
1736000
1737000
1738000
1739000
1740000
1741000
1742000
1743000
1744000
1745000
1746000
1747000
1748000
1749000
1750000
1751000
1752000
1753000
1754000
1755000
1756000
1757000
1758000
1759000
1760000
1761000
1762000
1763000
1764000
1765000
1766000
1767000
1768000
1769000
1770000
1771000
1772000
1773000
1774000
1775000
1776000
1777000
1778000
1779000
1780000
1781000
1782000
1783000
1784000
1785000
1786000
1787000
1788000
1789000
1790000
1791000
1792000
1793000
1794000
1795000
1796000
1797000
1798000
1799000
1800000
1801000
1802000
1803000
1804000
1805000
1806000
1807000
1808000
1809000
1810000
1811000
1812000
1813000
1814000
1815000
1816000
1817000
1818000
1819000

In [23]:
# concat_df =pd.DataFrame(np.vstack([from_to_df, from_to_df1]))
concat_df =pd.DataFrame(from_to_df)

In [24]:
concat_df.columns = ['trip_num','trip_id','from','to','date', 'travel_start','travel_end']
concat_df = concat_df[concat_df['from']!='nan']
concat_df = concat_df[concat_df['to']!='nan']

In [25]:
concat_df.shape

(95968, 7)

In [26]:
concat_df

,trip_num,trip_id,from,to,date,travel_start,travel_end
0,4,8da79163fc,DE,CH,2017-06-29 19:21:25,2017-06-24 21:38:12,2017-07-01 09:43:10
1,4,8da79163fc,CH,DE,2017-07-01 09:43:10,2017-06-24 21:38:12,2017-07-01 09:43:10
2,15,cb2ba27e67,DE,MT,2019-04-13 13:58:13,2019-04-13 13:58:13,2019-04-14 09:28:59
3,22,6a2de829da,US,CR,2019-01-05 00:21:08,2019-01-05 00:21:08,2019-01-11 22:23:52
4,25,24cf3c674d,PH,ES,2019-01-22 00:35:10,2019-01-22 00:35:10,2019-02-03 10:23:14
...,...,...,...,...,...,...,...
115835,29964,fde8ca4b0c,US,ZA,2019-03-03 00:50:24,2019-02-28 11:16:33,2019-03-04 01:05:09
115836,29964,fde8ca4b0c,ZA,RU,2019-03-03 11:42:14,2019-02-28 11:16:33,2019-03-04 01:05:09
115837,29964,fde8ca4b0c,RU,US,2019-03-03 23:06:24,2019-02-28 11:16:33,2019-03-04 01:05:09
115840,29979,2f4d864ae3,US,MX,2018-12-05 18:04:29,2018-12-04 20:47:14,2018-12-05 18:04:29
115841,29985,b33d052eab,SG,TH,2018-10-25 14:55:02,2018-10-25 03:37:32,2018-10-27 23:31:17

In [27]:
concat_df.to_csv("../csv/global_tripid_from_to.csv")

In [3]:
concat_df = pd.read_csv("../csv/global_from_to.csv")
travel_df = pd.read_csv("../csv/global_travel_df.csv")

In [4]:
from datetime import datetime
df = concat_df
df['date']= pd.to_datetime(df['date'])

In [5]:
# Initialize Graph model. 
G = nx.DiGraph()
nodes = travel_df['node'].unique().T
for u in nodes:
    for v in nodes:
        G.add_edge(u,v)
        G[u][v]['weight'] = 0

In [6]:
travel_df['node'].unique().T # 226 country

array(['US', 'EC', 'DE', 'CH', 'FR', 'VE', 'CO', 'BR', 'MT', 'ID', 'JP',
       'ZA', 'GB', 'NG', 'MX', 'CR', 'PH', 'ES', 'HK', 'HR', 'TW', 'AU',
       'CA', 'MA', 'IT', 'TR', 'TH', 'RU', 'NZ', 'CN', 'AR', 'PY', 'NL',
       'KW', nan, 'NO', 'PE', 'IN', 'SE', 'MD', 'KR', 'SA', 'CL', 'JO',
       'MY', 'SG', 'QA', 'AZ', 'UY', 'EG', 'DO', 'TT', 'JM', 'CZ', 'IE',
       'HU', 'VN', 'PT', 'IS', 'BE', 'AE', 'FI', 'PL', 'PR', 'AT', 'BG',
       'CU', 'GR', 'SV', 'GT', 'DK', 'FO', 'CY', 'MC', 'AG', 'MS', 'BM',
       'EE', 'LK', 'PK', 'PA', 'BS', 'RS', 'LV', 'AW', 'IL', 'ET', 'CD',
       'KE', 'UA', 'GU', 'KH', 'OM', 'BZ', 'VA', 'MO', 'RO', 'UZ', 'ZW',
       'BW', 'TZ', 'ME', 'AL', 'IR', 'TC', 'BH', 'UG', 'GH', 'SY', 'LB',
       'AD', 'MV', 'GY', 'SK', 'LU', 'LA', 'HN', 'AF', 'HT', 'SX', 'CW',
       'BN', 'SM', 'MM', 'GI', 'ZM', 'DZ', 'SI', 'MW', 'KY', 'SC', 'BO',
       'RE', 'GF', 'GP', 'TN', 'NP', 'BB', 'LT', 'BT', 'BL', 'BY', 'MN',
       'AI', 'MZ', 'BA', 'VI', 'AO', 'NI', 'SD', 'BD', 'KN', 'MQ', 'MF',
       'GE', 'KP', 'XK', 'SN', 'MU', 'KZ', 'IQ', 'IM', 'FM', 'MH', 'NC',
       'CI', 'KM', 'LI', 'TJ', 'RW', 'GD', 'LR', 'LC', 'MK', 'KG', 'CM',
       'PF', 'AM', 'VG', 'BJ', 'MG', 'AX', 'TD', 'AQ', 'BF', 'AS', 'WS',
       'SZ', 'SL', 'GL', 'LS', 'NE', 'GW', 'ML', 'LY', 'TM', 'PG', 'CF',
       'YE', 'MP', 'ER', 'GA', 'CG', 'JE', 'CV', 'GQ', 'BQ', 'TG', 'TL',
       'VC', 'TO', 'DJ', 'SB', 'SO', 'MR', 'SR', 'GM', 'DM', 'ST', 'GN',
       'BI', 'VU', 'YT', 'NU', 'FK', 'PW'], dtype=object)

In [9]:
# set(df['date'])
# pd.date_range('2018-01-01', periods=677, freq='D')

In [17]:
# Create a series of graphs by time
import copy
Tintervals = 200
w_slices = pd.date_range('2016-01-04', periods=Tintervals+1, freq='W')
time_dim = len(w_slices) -1 # subtract -1 becuase the number of time slices is less than time points by 1
serial_graphs = []
for t in range(0, time_dim):
    temp_G = copy.deepcopy(G) # we need a deep copy to create various graphs
    df_by_time = df[(df['date']>= w_slices[t])&(df['date']< w_slices[t+1])]
    def add_weight(u,v):
        if u!=v:
            temp_G[u][v]['weight'] +=1
        return 0
    df_by_time.apply(lambda x: add_weight(x['from'],x['to']), axis=1)
    serial_graphs.append(temp_G)

In [10]:
# # Create a series of graphs by date!
# import copy
# Tintervals = 677
# w_slices = pd.date_range('2018-01-01', periods=Tintervals, freq='D')
# time_dim = len(w_slices) -1 # subtract -1 becuase the number of time slices is less than time points by 1
# serial_graphs = []
# for t in range(0, time_dim):
#     temp_G = copy.deepcopy(G) # we need a deep copy to create various graphs
#     df_by_time = df[(df['date']>= w_slices[t])&(df['date']< w_slices[t+1])]
#     def add_weight(u,v):
#         if u!=v:
#             temp_G[u][v]['weight'] +=1
#         return 0
#     df_by_time.apply(lambda x: add_weight(x['from'],x['to']), axis=1)
#     serial_graphs.append(temp_G)

In [18]:
import pickle
def save_object(obj, filename):
    with open(filename, 'wb') as output:  # Overwrites any existing file.
        pickle.dump(obj, output, pickle.HIGHEST_PROTOCOL)

save_object(serial_graphs, '../pkl/global_weekly_graphs2.pkl')

In [19]:
import pickle
with open('../pkl/global_weekly_graphs2.pkl', 'rb') as f:
    serial_graphs  = pickle.load(f)

In [ ]:
# # # You may draw a graph 
# import matplotlib.pyplot as plt
# G = serial_graphs[1]
# edges,weights = zip(*nx.get_edge_attributes(G,'weight').items())
# pos = nx.spring_layout(G)
# colors = np.asarray(weights)
# colors = np.log(colors+0.001)-min(np.log(colors+0.001))
# plt.figure(figsize=(12,12)) 
# nx.draw(G, pos, node_color='#A0CBE2', edgelist=edges, edge_color=colors, with_labels = True, edge_cmap=plt.get_cmap('Reds'))
# print("trips between",week_slices[1],"and",week_slices[2])
# plt.show()

In [20]:
# Create tensors whose dimension is Time x Nodes x Featrues
# Here we refer the paper of 'Anomaly detection in spatiotemporal data via regularized non-negative tensor analysis'
# The number of features = 2 x the number of Nodes
import tensorly.backend as T
time_dim # the number of slices by time which we set above.
n_nodes = travel_df['node'].unique().size
tensor = T.tensor(np.zeros(Tintervals * n_nodes * 2*n_nodes).reshape((Tintervals, n_nodes, 2*n_nodes))) # Time x Nodes x Features

In [21]:
# Fill the Tensors
for i in range(0,time_dim):    
    mat = nx.adjacency_matrix(serial_graphs[i]).todense()
    feature_mat = np.hstack((mat, mat.T)) # Feature matrix.
    tensor[i] = feature_mat
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199

In [14]:
# mat = nx.adjacency_matrix(serial_graphs[100]).todense()
# feature_mat = np.hstack((mat, mat.T))

In [22]:
import pickle
import os
# os.chdir('/Users/bluethou/Thesis2020/thesis_pooreumoe_kim/code')
print(os.getcwd())
def save_object(obj, filename):
    with open(filename, 'wb') as output:  # Overwrites any existing file.
        pickle.dump(obj, output, pickle.HIGHEST_PROTOCOL)

save_object(tensor, '../pkl/global_weekly_tensor2.pkl')
# pickle.dump(tensor, file = open("travel_tensor.pickle", "wb"))

/Users/gimpuleumoe/Documents/TUM2020S/2020-pooreumoe-msc-thesis/code/Trip_mining

In [15]:
tensor.shape

(200, 226, 452)